import type { Metadata } from "next";
import "./globals.css";
// import { Inconsolata, Roboto, Quicksand, Jura, Sen } from "next/font/google";


// const quicksand = Quicksand({
//   variable: '--font-quicksand',
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['700']
// })

// //         MONOSPACE
// const inconsolata = Inconsolata({ subsets: ['latin'], variable: "--font-inconsolata" });
// //          NORMAL
// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['500']
// })
// //           LIGHT
// const jura = Jura({
//   variable: '--font-jura',
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['300']
// })
// const sen = Sen({
//   variable: '--font-sen',
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['800']
// })


export const metadata: Metadata = {
  title: "Corporación Ejecutiva Internacional",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`bg-[url('/resources/spain-beach-new.jpeg')] antialiased`}>
        {children}
      </body>
    </html>
  );
}